package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 25 13:46:17 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MsfLetter_VORowImpl extends ViewRowImpl {


    public static final int ENTITY_MSFLETTER_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ApprovalStatus,
        ApproverComments,
        BankAddress1,
        BankAddress2,
        BankLetter,
        BusinessUnitId,
        Comments,
        CreatedBy,
        CreationDate,
        EntitledAmount,
        ErrorMsg,
        GrossSalary,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        LoanAmount,
        LoanEffectiveDate,
        MsfLetter,
        MsfRecipientDesignation,
        MsfRecipientName,
        MsfRequestDate,
        MsfRequestId,
        MsfRequestNo,
        NextApprover,
        PayrollBatchName,
        PersonId,
        PreviousApprover,
        SoaFlowid,
        BankName,
        BankAccNumber,
        RequestType,
        Name_Trns,
        Number_Trns,
        Email_Trns,
        Group_Trns,
        Trans_Cadre,
        Trans_AssignmentType,
        Trans_Value,
        Employee_View_ROVO,
        Bank_ROVO,
        MSF_ROVO;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int APPROVALSTATUS = AttributesEnum.ApprovalStatus.index();
    public static final int APPROVERCOMMENTS = AttributesEnum.ApproverComments.index();
    public static final int BANKADDRESS1 = AttributesEnum.BankAddress1.index();
    public static final int BANKADDRESS2 = AttributesEnum.BankAddress2.index();
    public static final int BANKLETTER = AttributesEnum.BankLetter.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int ENTITLEDAMOUNT = AttributesEnum.EntitledAmount.index();
    public static final int ERRORMSG = AttributesEnum.ErrorMsg.index();
    public static final int GROSSSALARY = AttributesEnum.GrossSalary.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LOANAMOUNT = AttributesEnum.LoanAmount.index();
    public static final int LOANEFFECTIVEDATE = AttributesEnum.LoanEffectiveDate.index();
    public static final int MSFLETTER = AttributesEnum.MsfLetter.index();
    public static final int MSFRECIPIENTDESIGNATION = AttributesEnum.MsfRecipientDesignation.index();
    public static final int MSFRECIPIENTNAME = AttributesEnum.MsfRecipientName.index();
    public static final int MSFREQUESTDATE = AttributesEnum.MsfRequestDate.index();
    public static final int MSFREQUESTID = AttributesEnum.MsfRequestId.index();
    public static final int MSFREQUESTNO = AttributesEnum.MsfRequestNo.index();
    public static final int NEXTAPPROVER = AttributesEnum.NextApprover.index();
    public static final int PAYROLLBATCHNAME = AttributesEnum.PayrollBatchName.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int PREVIOUSAPPROVER = AttributesEnum.PreviousApprover.index();
    public static final int SOAFLOWID = AttributesEnum.SoaFlowid.index();
    public static final int BANKNAME = AttributesEnum.BankName.index();
    public static final int BANKACCNUMBER = AttributesEnum.BankAccNumber.index();
    public static final int REQUESTTYPE = AttributesEnum.RequestType.index();
    public static final int NAME_TRNS = AttributesEnum.Name_Trns.index();
    public static final int NUMBER_TRNS = AttributesEnum.Number_Trns.index();
    public static final int EMAIL_TRNS = AttributesEnum.Email_Trns.index();
    public static final int GROUP_TRNS = AttributesEnum.Group_Trns.index();
    public static final int TRANS_CADRE = AttributesEnum.Trans_Cadre.index();
    public static final int TRANS_ASSIGNMENTTYPE = AttributesEnum.Trans_AssignmentType.index();
    public static final int TRANS_VALUE = AttributesEnum.Trans_Value.index();
    public static final int EMPLOYEE_VIEW_ROVO = AttributesEnum.Employee_View_ROVO.index();
    public static final int BANK_ROVO = AttributesEnum.Bank_ROVO.index();
    public static final int MSF_ROVO = AttributesEnum.MSF_ROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MsfLetter_VORowImpl() {
    }

    /**
     * Gets MsfLetter_EO entity object.
     * @return the MsfLetter_EO
     */
    public EntityImpl getMsfLetter_EO() {
        return (EntityImpl) getEntity(ENTITY_MSFLETTER_EO);
    }

    /**
     * Gets the attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @return the APPROVAL_STATUS
     */
    public String getApprovalStatus() {
        return (String) getAttributeInternal(APPROVALSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @param value value to set the APPROVAL_STATUS
     */
    public void setApprovalStatus(String value) {
        setAttributeInternal(APPROVALSTATUS, value);
    }

    /**
     * Gets the attribute value for APPROVER_COMMENTS using the alias name ApproverComments.
     * @return the APPROVER_COMMENTS
     */
    public String getApproverComments() {
        return (String) getAttributeInternal(APPROVERCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVER_COMMENTS using the alias name ApproverComments.
     * @param value value to set the APPROVER_COMMENTS
     */
    public void setApproverComments(String value) {
        setAttributeInternal(APPROVERCOMMENTS, value);
    }

    /**
     * Gets the attribute value for BANK_ADDRESS1 using the alias name BankAddress1.
     * @return the BANK_ADDRESS1
     */
    public String getBankAddress1() {
        return (String) getAttributeInternal(BANKADDRESS1);
    }

    /**
     * Sets <code>value</code> as attribute value for BANK_ADDRESS1 using the alias name BankAddress1.
     * @param value value to set the BANK_ADDRESS1
     */
    public void setBankAddress1(String value) {
        setAttributeInternal(BANKADDRESS1, value);
    }

    /**
     * Gets the attribute value for BANK_ADDRESS2 using the alias name BankAddress2.
     * @return the BANK_ADDRESS2
     */
    public String getBankAddress2() {
        return (String) getAttributeInternal(BANKADDRESS2);
    }

    /**
     * Sets <code>value</code> as attribute value for BANK_ADDRESS2 using the alias name BankAddress2.
     * @param value value to set the BANK_ADDRESS2
     */
    public void setBankAddress2(String value) {
        setAttributeInternal(BANKADDRESS2, value);
    }

    /**
     * Gets the attribute value for BANK_LETTER using the alias name BankLetter.
     * @return the BANK_LETTER
     */
    public String getBankLetter() {
        return (String) getAttributeInternal(BANKLETTER);
    }

    /**
     * Sets <code>value</code> as attribute value for BANK_LETTER using the alias name BankLetter.
     * @param value value to set the BANK_LETTER
     */
    public void setBankLetter(String value) {
        setAttributeInternal(BANKLETTER, value);
    }


    /**
     * Gets the attribute value for the calculated attribute BankName.
     * @return the BankName
     */
    public String getBankName() {
        return (String) getAttributeInternal(BANKNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for BANK_NAME using the alias name BankName.
     * @param value value to set the BANK_NAME
     */
    public void setBankName(String value) {
        setAttributeInternal(BANKNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BankAccNumber.
     * @return the BankAccNumber
     */
    public String getBankAccNumber() {
        return (String) getAttributeInternal(BANKACCNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for BANK_ACC_NUMBER using the alias name BankAccNumber.
     * @param value value to set the BANK_ACC_NUMBER
     */
    public void setBankAccNumber(String value) {
        setAttributeInternal(BANKACCNUMBER, value);
    }


    /**
     * Gets the attribute value for the calculated attribute RequestType.
     * @return the RequestType
     */
    public String getRequestType() {
        return (String) getAttributeInternal(REQUESTTYPE);
    }

    /**
     * Gets the attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @return the BUSINESS_UNIT_ID
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal) getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @param value value to set the BUSINESS_UNIT_ID
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for ENTITLED_AMOUNT using the alias name EntitledAmount.
     * @return the ENTITLED_AMOUNT
     */
    public BigDecimal getEntitledAmount() {
        BigDecimal gross = new BigDecimal(0);
        BigDecimal entAmt = new BigDecimal(0);
        gross = getGrossSalary() != null ? getGrossSalary() :  new BigDecimal(0);
//        entAmt =gross.multiply(new BigDecimal(0.3)) ; 
//        return  entAmt.multiply(new BigDecimal(10));
      //  gross = getGrossSalary();
              entAmt = gross.multiply(new BigDecimal(3)); 
              return (BigDecimal)entAmt;
        
//        return (BigDecimal) getAttributeInternal(ENTITLEDAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for ENTITLED_AMOUNT using the alias name EntitledAmount.
     * @param value value to set the ENTITLED_AMOUNT
     */
    public void setEntitledAmount(BigDecimal value) {
        setAttributeInternal(ENTITLEDAMOUNT, value);
    }

    /**
     * Gets the attribute value for ERROR_MSG using the alias name ErrorMsg.
     * @return the ERROR_MSG
     */
    public ClobDomain getErrorMsg() {
        return (ClobDomain) getAttributeInternal(ERRORMSG);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_MSG using the alias name ErrorMsg.
     * @param value value to set the ERROR_MSG
     */
    public void setErrorMsg(ClobDomain value) {
        setAttributeInternal(ERRORMSG, value);
    }

    /**
     * Gets the attribute value for GROSS_SALARY using the alias name GrossSalary.
     * @return the GROSS_SALARY
     */
    public BigDecimal getGrossSalary() {
        BigDecimal type = null; 
        String name = "0";
        if (getPersonId() != null) {
        type = (BigDecimal)getPersonId();
        Row[] orgRows;
        orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
        if (orgRows.length > 0) {
        name = orgRows[0].getAttribute("SalaryAmount").toString();
        }
        
        return new BigDecimal(name);
        } else {
            return (BigDecimal) getAttributeInternal(GROSSSALARY);
            }  
    }

    /**
     * Sets <code>value</code> as attribute value for GROSS_SALARY using the alias name GrossSalary.
     * @param value value to set the GROSS_SALARY
     */
    public void setGrossSalary(BigDecimal value) {
        setAttributeInternal(GROSSSALARY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LOAN_AMOUNT using the alias name LoanAmount.
     * @return the LOAN_AMOUNT
     */
    public BigDecimal getLoanAmount() {
        return (BigDecimal) getAttributeInternal(LOANAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for LOAN_AMOUNT using the alias name LoanAmount.
     * @param value value to set the LOAN_AMOUNT
     */
    public void setLoanAmount(BigDecimal value) {
        setAttributeInternal(LOANAMOUNT, value);
    }

    /**
     * Gets the attribute value for LOAN_EFFECTIVE_DATE using the alias name LoanEffectiveDate.
     * @return the LOAN_EFFECTIVE_DATE
     */
    public Timestamp getLoanEffectiveDate() {
        return (Timestamp) getAttributeInternal(LOANEFFECTIVEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LOAN_EFFECTIVE_DATE using the alias name LoanEffectiveDate.
     * @param value value to set the LOAN_EFFECTIVE_DATE
     */
    public void setLoanEffectiveDate(Timestamp value) {
        setAttributeInternal(LOANEFFECTIVEDATE, value);
    }

    /**
     * Gets the attribute value for MSF_LETTER using the alias name MsfLetter.
     * @return the MSF_LETTER
     */
    public String getMsfLetter() {
        return (String) getAttributeInternal(MSFLETTER);
    }

    /**
     * Sets <code>value</code> as attribute value for MSF_LETTER using the alias name MsfLetter.
     * @param value value to set the MSF_LETTER
     */
    public void setMsfLetter(String value) {
        setAttributeInternal(MSFLETTER, value);
    }

    /**
     * Gets the attribute value for MSF_RECIPIENT_DESIGNATION using the alias name MsfRecipientDesignation.
     * @return the MSF_RECIPIENT_DESIGNATION
     */
    public String getMsfRecipientDesignation() {
        return (String) getAttributeInternal(MSFRECIPIENTDESIGNATION);
    }

    /**
     * Sets <code>value</code> as attribute value for MSF_RECIPIENT_DESIGNATION using the alias name MsfRecipientDesignation.
     * @param value value to set the MSF_RECIPIENT_DESIGNATION
     */
    public void setMsfRecipientDesignation(String value) {
        setAttributeInternal(MSFRECIPIENTDESIGNATION, value);
    }

    /**
     * Gets the attribute value for MSF_RECIPIENT_NAME using the alias name MsfRecipientName.
     * @return the MSF_RECIPIENT_NAME
     */
    public String getMsfRecipientName() {
        return (String) getAttributeInternal(MSFRECIPIENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for MSF_RECIPIENT_NAME using the alias name MsfRecipientName.
     * @param value value to set the MSF_RECIPIENT_NAME
     */
    public void setMsfRecipientName(String value) {
        setAttributeInternal(MSFRECIPIENTNAME, value);
    }

    /**
     * Gets the attribute value for MSF_REQUEST_DATE using the alias name MsfRequestDate.
     * @return the MSF_REQUEST_DATE
     */
    public Timestamp getMsfRequestDate() {
        return (Timestamp) getAttributeInternal(MSFREQUESTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MSF_REQUEST_DATE using the alias name MsfRequestDate.
     * @param value value to set the MSF_REQUEST_DATE
     */
    public void setMsfRequestDate(Timestamp value) {
        setAttributeInternal(MSFREQUESTDATE, value);
    }

    /**
     * Gets the attribute value for MSF_REQUEST_ID using the alias name MsfRequestId.
     * @return the MSF_REQUEST_ID
     */
    public BigDecimal getMsfRequestId() {
        return (BigDecimal) getAttributeInternal(MSFREQUESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for MSF_REQUEST_ID using the alias name MsfRequestId.
     * @param value value to set the MSF_REQUEST_ID
     */
    public void setMsfRequestId(BigDecimal value) {
        setAttributeInternal(MSFREQUESTID, value);
    }

    /**
     * Gets the attribute value for MSF_REQUEST_NO using the alias name MsfRequestNo.
     * @return the MSF_REQUEST_NO
     */
    public String getMsfRequestNo() {
        return (String) getAttributeInternal(MSFREQUESTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for MSF_REQUEST_NO using the alias name MsfRequestNo.
     * @param value value to set the MSF_REQUEST_NO
     */
    public void setMsfRequestNo(String value) {
        setAttributeInternal(MSFREQUESTNO, value);
    }

    /**
     * Gets the attribute value for NEXT_APPROVER using the alias name NextApprover.
     * @return the NEXT_APPROVER
     */
    public String getNextApprover() {
        return (String) getAttributeInternal(NEXTAPPROVER);
    }

    /**
     * Sets <code>value</code> as attribute value for NEXT_APPROVER using the alias name NextApprover.
     * @param value value to set the NEXT_APPROVER
     */
    public void setNextApprover(String value) {
        setAttributeInternal(NEXTAPPROVER, value);
    }

    /**
     * Gets the attribute value for PAYROLL_BATCH_NAME using the alias name PayrollBatchName.
     * @return the PAYROLL_BATCH_NAME
     */
    public String getPayrollBatchName() {
        return (String) getAttributeInternal(PAYROLLBATCHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYROLL_BATCH_NAME using the alias name PayrollBatchName.
     * @param value value to set the PAYROLL_BATCH_NAME
     */
    public void setPayrollBatchName(String value) {
        setAttributeInternal(PAYROLLBATCHNAME, value);
    }

    /**
     * Gets the attribute value for PERSON_ID using the alias name PersonId.
     * @return the PERSON_ID
     */
    public BigDecimal getPersonId() {
        return (BigDecimal) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId.
     * @param value value to set the PERSON_ID
     */
    public void setPersonId(BigDecimal value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for PREVIOUS_APPROVER using the alias name PreviousApprover.
     * @return the PREVIOUS_APPROVER
     */
    public String getPreviousApprover() {
        return (String) getAttributeInternal(PREVIOUSAPPROVER);
    }

    /**
     * Sets <code>value</code> as attribute value for PREVIOUS_APPROVER using the alias name PreviousApprover.
     * @param value value to set the PREVIOUS_APPROVER
     */
    public void setPreviousApprover(String value) {
        setAttributeInternal(PREVIOUSAPPROVER, value);
    }

    /**
     * Gets the attribute value for SOA_FLOWID using the alias name SoaFlowid.
     * @return the SOA_FLOWID
     */
    public BigDecimal getSoaFlowid() {
        return (BigDecimal) getAttributeInternal(SOAFLOWID);
    }

    /**
     * Sets <code>value</code> as attribute value for SOA_FLOWID using the alias name SoaFlowid.
     * @param value value to set the SOA_FLOWID
     */
    public void setSoaFlowid(BigDecimal value) {
        setAttributeInternal(SOAFLOWID, value);
    }


    /**
     * Gets the attribute value for the calculated attribute Name_Trns.
     * @return the Name_Trns
     */
    public String getName_Trns() {

        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("DisplayName").toString();
            }
            return name;
        } else {

            return (String) getAttributeInternal(NAME_TRNS);
        }


    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Name_Trns.
     * @param value value to set the  Name_Trns
     */
    public void setName_Trns(String value) {
        setAttributeInternal(NAME_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Number_Trns.
     * @return the Number_Trns
     */
    public String getNumber_Trns() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("PersonNumber").toString();
            }
            return name;
        } else {
            return (String) getAttributeInternal(NUMBER_TRNS);

        }


    }


    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Number_Trns.
     * @param value value to set the  Number_Trns
     */
    public void setNumber_Trns(String value) {
        setAttributeInternal(NUMBER_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Email_Trns.
     * @return the Email_Trns
     */
    public String getEmail_Trns() {
        
                                                        
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
        type = (BigDecimal)getPersonId();
        Row[] orgRows;
        orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
        if (orgRows.length > 0) {
        name = orgRows[0].getAttribute("EmailAddress").toString();
        }
        return name;
                                } else {
                                                    return (String) getAttributeInternal(EMAIL_TRNS);
                                                }
        }


    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Email_Trns.
     * @param value value to set the  Email_Trns
     */
    public void setEmail_Trns(String value) {
        setAttributeInternal(EMAIL_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Group_Trns.
     * @return the Group_Trns
     */
    public String getGroup_Trns() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("BusinessUnitName").toString();
            }
            return name;
        } else {
            return (String) getAttributeInternal(GROUP_TRNS);
        }
        
        }


    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Group_Trns.
     * @param value value to set the  Group_Trns
     */
    public void setGroup_Trns(String value) {
        setAttributeInternal(GROUP_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Cadre.
     * @return the Trans_Cadre
     */
    public String getTrans_Cadre() {

        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("Cadre").toString();
            }
            return name;
        } else {

        return (String) getAttributeInternal(TRANS_CADRE);}
    }


    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Cadre.
     * @param value value to set the  Trans_Cadre
     */
    public void setTrans_Cadre(String value) {
        setAttributeInternal(TRANS_CADRE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_AssignmentType.
     * @return the Trans_AssignmentType
     */
    public String getTrans_AssignmentType() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("AssignmentType").toString();
            }
            return name;
        } else {
        return (String) getAttributeInternal(TRANS_ASSIGNMENTTYPE);}
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_AssignmentType.
     * @param value value to set the  Trans_AssignmentType
     */
    public void setTrans_AssignmentType(String value) {
        setAttributeInternal(TRANS_ASSIGNMENTTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Value.
     * @return the Trans_Value
     */
    public String getTrans_Value() {

        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("FullPartTime").toString();
            }
            return name;
        } else {

        return (String) getAttributeInternal(TRANS_VALUE);}
    }


    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Value.
     * @param value value to set the  Trans_Value
     */
    public void setTrans_Value(String value) {
        setAttributeInternal(TRANS_VALUE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Employee_View_ROVO.
     */
    public RowSet getEmployee_View_ROVO() {
        return (RowSet) getAttributeInternal(EMPLOYEE_VIEW_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Bank_ROVO.
     */
    public RowSet getBank_ROVO() {
        return (RowSet) getAttributeInternal(BANK_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MSF_ROVO.
     */
    public RowSet getMSF_ROVO() {
        return (RowSet) getAttributeInternal(MSF_ROVO);
    }


}

