package model.ro;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 26 09:37:08 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Loopup_Types_ROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        LookupTypeId,
        LookupTypeCode,
        LookupTypeName,
        LookupTypeNameDispTl,
        AccessLevel,
        ActiveYn,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        ParentTypeId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int LOOKUPTYPEID = AttributesEnum.LookupTypeId.index();
    public static final int LOOKUPTYPECODE = AttributesEnum.LookupTypeCode.index();
    public static final int LOOKUPTYPENAME = AttributesEnum.LookupTypeName.index();
    public static final int LOOKUPTYPENAMEDISPTL = AttributesEnum.LookupTypeNameDispTl.index();
    public static final int ACCESSLEVEL = AttributesEnum.AccessLevel.index();
    public static final int ACTIVEYN = AttributesEnum.ActiveYn.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int PARENTTYPEID = AttributesEnum.ParentTypeId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public Loopup_Types_ROVORowImpl() {
    }
}

